version: "3.5"
services:
    main:
        container_name: ${PKG_NAME}
        image: ${DOCKER_REPO}/${DOCKER_IMAGE}:${VERSION}
        user: root
        build:
            context: ./
            dockerfile: Dockerfile
            target: ${ENV}_stage
            args:
                - PKG_NAME
        ports:
            # for gazebo VNC forwarding
            - "0.0.0.0:5900:5900"
        volumes:
            # bind mount to the local resources directory for development
            - .:/root/catkin_ws/src/${PKG_NAME}
            # sound
            - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie
            # gazebo
            - /tmp/.gazebo/:/root/.gazebo/
            # X11 forwarding
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        environment:
            #  uncomment to use Xquartz for things like the graph and turtle sim
            # - DISPLAY=${HOST_IP}:0
            #  uncomment to use VNC Viewer for Gazebo and Rviz
            - DISPLAY=:1.0
            - QT_X11_NO_MITSHM=1
            - PULSE_SERVER=${HOST_IP}
            - HOST_IP=${HOST_IP}
        # allows us to attach to the container and examine it in development
        stdin_open: true
        tty: true
        # make sure the docker container comes back up when it goes down automatically
        restart: always
