version: "3.5"
services:
    main:
        container_name: ${PKG_NAME}
        image: ${DOCKER_REPO}/${DOCKER_IMAGE}:${VERSION}
        user: root
        build:
            context: ./
            dockerfile: Dockerfile
            target: ${ENV}_stage
            args:
                - PKG_NAME
        ports:
            # for gazebo VNC forwarding
            - "0.0.0.0:5900:5900"
        volumes:
            # bind mount to the local resources directory for development
            - .:/root/catkin_ws/src/${PKG_NAME}
            # # sound
            # - ~/.config/pulse:/home/pulseaudio/.config/pulse
            # gazebo
            - /tmp/.gazebo/:/root/.gazebo/
            # X11 forwarding
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        environment:
            # - DISPLAY=${HOST_IP}:0
            - DISPLAY=:1.0
            - QT_X11_NO_MITSHM=1
            # - PULSE_SERVER=host.docker.internal
        # allows us to attach to the container and examine it in development
        stdin_open: true
        tty: true
        # make sure the docker container comes back up when it goes down automatically
        restart: always
